// This file is generated by Slice Machine. Update with care!

import DetailMedia from './DetailMedia';
import DetailText from './DetailText';

export {
	DetailMedia,
	DetailText,
};

export const components = {
	detail_media: DetailMedia,
	detail_text: DetailText,
};
