// This file is generated by Slice Machine. Update with care!

import DetailMainText from './DetailMainText';
import DetailMedia from './DetailMedia';
import DetailMedia1X1 from './DetailMedia1X1';
import DetailMedia9X16 from './DetailMedia9X16';
import DetailText from './DetailText';

export {
	DetailMainText,
	DetailMedia,
	DetailMedia1X1,
	DetailMedia9X16,
	DetailText,
};

export const components = {
	detail_main_text: DetailMainText,
	detail_media: DetailMedia,
	detail_media1_x1: DetailMedia1X1,
	detail_media9_x16: DetailMedia9X16,
	detail_text: DetailText,
};
